language: node_js

node_js:
  - "0.10"

sudo: required

before_script:
	- echo 'angular.module("SMSApp").constant("APP_ENV", {"loginRequired":false,"authClient":"http://oauthclient.gosms.io/","api":"http://localhost:3000/"}).constant("VERSION", "0.4.0");' > assets/js/config/config.js
    - npm install -g karma-cli
    - export NODE_ENV='development'
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm start > /dev/null &
    - npm run update-webdriver
   	- sleep 1
                  
script:
    - karma start karma.conf.js --single-run --reporters=dots
