language: node_js
node_js:
  - 0.10

before_script:
  - export DISPLAY=:99.0
  - export NODE_ENV='development'
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1

script:
  - karma start karma.conf.js --single-run --reporters=dots


