language: node_js

node_js:
  - "0.10"

sudo: required

before_script:
    - npm install -g karma-cli
    - export NODE_ENV='development'
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm start > /dev/null &
   	- sleep 1
                  
script:
    - karma start karma.conf.js --single-run --reporters=dots
